# -*- coding: utf-8 -*-

# DO NOT EDIT THIS FILE!
# This file has been autogenerated by dephell <3
# https://github.com/dephell/dephell

try:
    from setuptools import setup
except ImportError:
    from distutils.core import setup

import os.path

readme = ''
here = os.path.abspath(os.path.dirname(__file__))
readme_path = os.path.join(here, 'README.rst')
if os.path.exists(readme_path):
    with open(readme_path, 'rb') as stream:
        readme = stream.read().decode('utf8')

setup(
    long_description=readme,
    name='imageedit',
    version='2020.5',
    description='Create various icon masks and shading effects with the imageedit library',
    python_requires='==3.*,>=3.6.0',
    project_urls={
        "documentation":
            "https://github.com/FredHappyface/Python.ImageEdit/blob/master/README.md",
        "homepage":
            "https://github.com/FredHappyface/Python.ImageEdit",
        "repository":
            "https://github.com/FredHappyface/Python.ImageEdit"
    },
    author='FredHappyface',
    classifiers=[
        'Development Status :: 5 - Production/Stable',
        'Intended Audience :: Developers', 'Intended Audience :: Education',
        'License :: OSI Approved :: MIT License', 'Natural Language :: English',
        'Operating System :: OS Independent',
        'Programming Language :: Python :: 3',
        'Programming Language :: Python :: 3.6',
        'Programming Language :: Python :: 3.7',
        'Programming Language :: Python :: 3.8',
        'Programming Language :: Python :: Implementation :: CPython',
        'Topic :: Multimedia :: Graphics',
        'Topic :: Software Development :: Libraries :: Python Modules',
        'Topic :: Utilities'
    ],
    packages=['imageedit'],
    package_dir={"": "."},
    package_data={"imageedit": ["resources/*.ttf"]},
    install_requires=[
        'blendmodes==2020.*,>=2020.2.1', 'colourswatch==2020.*,>=2020.1.0',
        'layeredimage==2020.*,>=2020.5.6', 'metprint==2020.*,>=2020.6.1',
        'pillow==7.*,>=7.1.2', 'svgtrace==2020.*,>=2020.0.2'
    ],
)
